/*
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.gameuno.services.UnoDslGrammarAccess;

@SuppressWarnings("all")
public class UnoDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected UnoDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_CarteActive_CarteInversionKeyword_0_2_or_CartePasserTourKeyword_0_0_or_CartePlus2Keyword_0_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (UnoDslGrammarAccess) access;
		match_CarteActive_CarteInversionKeyword_0_2_or_CartePasserTourKeyword_0_0_or_CartePlus2Keyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getCarteActiveAccess().getCarteInversionKeyword_0_2()), new TokenAlias(false, false, grammarAccess.getCarteActiveAccess().getCartePasserTourKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getCarteActiveAccess().getCartePlus2Keyword_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getCarteNoireRule())
			return getCarteNoireToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * CarteNoire:
	 * 	('carte-plus-4' | 'carte-joker' | 'carte-uno')
	 * ;
	 */
	protected String getCarteNoireToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "carte-plus-4";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_CarteActive_CarteInversionKeyword_0_2_or_CartePasserTourKeyword_0_0_or_CartePlus2Keyword_0_1.equals(syntax))
				emit_CarteActive_CarteInversionKeyword_0_2_or_CartePasserTourKeyword_0_0_or_CartePlus2Keyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'carte-passer-tour' | 'carte-plus-2' | 'carte-inversion'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '-couleur-' couleur=CouleurCarte
	 */
	protected void emit_CarteActive_CarteInversionKeyword_0_2_or_CartePasserTourKeyword_0_0_or_CartePlus2Keyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
