/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Carte</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gameuno.unoDsl.Carte#getCouleur <em>Couleur</em>}</li>
 * </ul>
 *
 * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getCarte()
 * @model
 * @generated
 */
public interface Carte extends EObject
{
  /**
   * Returns the value of the '<em><b>Couleur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Couleur</em>' attribute.
   * @see #setCouleur(String)
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getCarte_Couleur()
   * @model
   * @generated
   */
  String getCouleur();

  /**
   * Sets the value of the '{@link org.xtext.gameuno.unoDsl.Carte#getCouleur <em>Couleur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Couleur</em>' attribute.
   * @see #getCouleur()
   * @generated
   */
  void setCouleur(String value);

} // Carte
