/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Carte Active</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getCarteActive()
 * @model
 * @generated
 */
public interface CarteActive extends Carte
{
} // CarteActive
