/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Carte Classique</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gameuno.unoDsl.CarteClassique#getNumeroCarte <em>Numero Carte</em>}</li>
 * </ul>
 *
 * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getCarteClassique()
 * @model
 * @generated
 */
public interface CarteClassique extends Carte
{
  /**
   * Returns the value of the '<em><b>Numero Carte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numero Carte</em>' attribute.
   * @see #setNumeroCarte(int)
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getCarteClassique_NumeroCarte()
   * @model
   * @generated
   */
  int getNumeroCarte();

  /**
   * Sets the value of the '{@link org.xtext.gameuno.unoDsl.CarteClassique#getNumeroCarte <em>Numero Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Numero Carte</em>' attribute.
   * @see #getNumeroCarte()
   * @generated
   */
  void setNumeroCarte(int value);

} // CarteClassique
