/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exigence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gameuno.unoDsl.Exigence#getExpr1 <em>Expr1</em>}</li>
 *   <li>{@link org.xtext.gameuno.unoDsl.Exigence#getLinker1 <em>Linker1</em>}</li>
 *   <li>{@link org.xtext.gameuno.unoDsl.Exigence#getLinker2 <em>Linker2</em>}</li>
 *   <li>{@link org.xtext.gameuno.unoDsl.Exigence#getCarte <em>Carte</em>}</li>
 *   <li>{@link org.xtext.gameuno.unoDsl.Exigence#getLinker3 <em>Linker3</em>}</li>
 *   <li>{@link org.xtext.gameuno.unoDsl.Exigence#getExpr2 <em>Expr2</em>}</li>
 * </ul>
 *
 * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getExigence()
 * @model
 * @generated
 */
public interface Exigence extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr1</em>' attribute.
   * @see #setExpr1(String)
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getExigence_Expr1()
   * @model
   * @generated
   */
  String getExpr1();

  /**
   * Sets the value of the '{@link org.xtext.gameuno.unoDsl.Exigence#getExpr1 <em>Expr1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr1</em>' attribute.
   * @see #getExpr1()
   * @generated
   */
  void setExpr1(String value);

  /**
   * Returns the value of the '<em><b>Linker1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Linker1</em>' attribute.
   * @see #setLinker1(String)
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getExigence_Linker1()
   * @model
   * @generated
   */
  String getLinker1();

  /**
   * Sets the value of the '{@link org.xtext.gameuno.unoDsl.Exigence#getLinker1 <em>Linker1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Linker1</em>' attribute.
   * @see #getLinker1()
   * @generated
   */
  void setLinker1(String value);

  /**
   * Returns the value of the '<em><b>Linker2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Linker2</em>' attribute.
   * @see #setLinker2(String)
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getExigence_Linker2()
   * @model
   * @generated
   */
  String getLinker2();

  /**
   * Sets the value of the '{@link org.xtext.gameuno.unoDsl.Exigence#getLinker2 <em>Linker2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Linker2</em>' attribute.
   * @see #getLinker2()
   * @generated
   */
  void setLinker2(String value);

  /**
   * Returns the value of the '<em><b>Carte</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.gameuno.unoDsl.Carte}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte</em>' containment reference list.
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getExigence_Carte()
   * @model containment="true"
   * @generated
   */
  EList<Carte> getCarte();

  /**
   * Returns the value of the '<em><b>Linker3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Linker3</em>' attribute.
   * @see #setLinker3(String)
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getExigence_Linker3()
   * @model
   * @generated
   */
  String getLinker3();

  /**
   * Sets the value of the '{@link org.xtext.gameuno.unoDsl.Exigence#getLinker3 <em>Linker3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Linker3</em>' attribute.
   * @see #getLinker3()
   * @generated
   */
  void setLinker3(String value);

  /**
   * Returns the value of the '<em><b>Expr2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr2</em>' attribute.
   * @see #setExpr2(String)
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getExigence_Expr2()
   * @model
   * @generated
   */
  String getExpr2();

  /**
   * Sets the value of the '{@link org.xtext.gameuno.unoDsl.Exigence#getExpr2 <em>Expr2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr2</em>' attribute.
   * @see #getExpr2()
   * @generated
   */
  void setExpr2(String value);

} // Exigence
