/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.gameuno.unoDsl.UnoDslFactory
 * @model kind="package"
 * @generated
 */
public interface UnoDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "unoDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/gameuno/UnoDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "unoDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UnoDslPackage eINSTANCE = org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.gameuno.unoDsl.impl.UnoDslImpl <em>Uno Dsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gameuno.unoDsl.impl.UnoDslImpl
   * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getUnoDsl()
   * @generated
   */
  int UNO_DSL = 0;

  /**
   * The feature id for the '<em><b>Regles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_DSL__REGLES = 0;

  /**
   * The number of structural features of the '<em>Uno Dsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_DSL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.gameuno.unoDsl.impl.RegleJeuImpl <em>Regle Jeu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gameuno.unoDsl.impl.RegleJeuImpl
   * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getRegleJeu()
   * @generated
   */
  int REGLE_JEU = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGLE_JEU__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGLE_JEU__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Exigence</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGLE_JEU__EXIGENCE = 2;

  /**
   * The number of structural features of the '<em>Regle Jeu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGLE_JEU_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.gameuno.unoDsl.impl.ExigenceImpl <em>Exigence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gameuno.unoDsl.impl.ExigenceImpl
   * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getExigence()
   * @generated
   */
  int EXIGENCE = 2;

  /**
   * The feature id for the '<em><b>Expr1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIGENCE__EXPR1 = 0;

  /**
   * The feature id for the '<em><b>Linker1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIGENCE__LINKER1 = 1;

  /**
   * The feature id for the '<em><b>Linker2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIGENCE__LINKER2 = 2;

  /**
   * The feature id for the '<em><b>Carte</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIGENCE__CARTE = 3;

  /**
   * The feature id for the '<em><b>Linker3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIGENCE__LINKER3 = 4;

  /**
   * The feature id for the '<em><b>Expr2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIGENCE__EXPR2 = 5;

  /**
   * The number of structural features of the '<em>Exigence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIGENCE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.gameuno.unoDsl.impl.CarteImpl <em>Carte</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gameuno.unoDsl.impl.CarteImpl
   * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getCarte()
   * @generated
   */
  int CARTE = 3;

  /**
   * The feature id for the '<em><b>Couleur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE__COULEUR = 0;

  /**
   * The number of structural features of the '<em>Carte</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.gameuno.unoDsl.impl.CarteClassiqueImpl <em>Carte Classique</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gameuno.unoDsl.impl.CarteClassiqueImpl
   * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getCarteClassique()
   * @generated
   */
  int CARTE_CLASSIQUE = 4;

  /**
   * The feature id for the '<em><b>Couleur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE_CLASSIQUE__COULEUR = CARTE__COULEUR;

  /**
   * The feature id for the '<em><b>Numero Carte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE_CLASSIQUE__NUMERO_CARTE = CARTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Carte Classique</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE_CLASSIQUE_FEATURE_COUNT = CARTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.gameuno.unoDsl.impl.CarteActiveImpl <em>Carte Active</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gameuno.unoDsl.impl.CarteActiveImpl
   * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getCarteActive()
   * @generated
   */
  int CARTE_ACTIVE = 5;

  /**
   * The feature id for the '<em><b>Couleur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE_ACTIVE__COULEUR = CARTE__COULEUR;

  /**
   * The number of structural features of the '<em>Carte Active</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE_ACTIVE_FEATURE_COUNT = CARTE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.gameuno.unoDsl.UnoDsl <em>Uno Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uno Dsl</em>'.
   * @see org.xtext.gameuno.unoDsl.UnoDsl
   * @generated
   */
  EClass getUnoDsl();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.gameuno.unoDsl.UnoDsl#getRegles <em>Regles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Regles</em>'.
   * @see org.xtext.gameuno.unoDsl.UnoDsl#getRegles()
   * @see #getUnoDsl()
   * @generated
   */
  EReference getUnoDsl_Regles();

  /**
   * Returns the meta object for class '{@link org.xtext.gameuno.unoDsl.RegleJeu <em>Regle Jeu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regle Jeu</em>'.
   * @see org.xtext.gameuno.unoDsl.RegleJeu
   * @generated
   */
  EClass getRegleJeu();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.RegleJeu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.gameuno.unoDsl.RegleJeu#getName()
   * @see #getRegleJeu()
   * @generated
   */
  EAttribute getRegleJeu_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.RegleJeu#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.gameuno.unoDsl.RegleJeu#getDescription()
   * @see #getRegleJeu()
   * @generated
   */
  EAttribute getRegleJeu_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.gameuno.unoDsl.RegleJeu#getExigence <em>Exigence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exigence</em>'.
   * @see org.xtext.gameuno.unoDsl.RegleJeu#getExigence()
   * @see #getRegleJeu()
   * @generated
   */
  EReference getRegleJeu_Exigence();

  /**
   * Returns the meta object for class '{@link org.xtext.gameuno.unoDsl.Exigence <em>Exigence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exigence</em>'.
   * @see org.xtext.gameuno.unoDsl.Exigence
   * @generated
   */
  EClass getExigence();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.Exigence#getExpr1 <em>Expr1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expr1</em>'.
   * @see org.xtext.gameuno.unoDsl.Exigence#getExpr1()
   * @see #getExigence()
   * @generated
   */
  EAttribute getExigence_Expr1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.Exigence#getLinker1 <em>Linker1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Linker1</em>'.
   * @see org.xtext.gameuno.unoDsl.Exigence#getLinker1()
   * @see #getExigence()
   * @generated
   */
  EAttribute getExigence_Linker1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.Exigence#getLinker2 <em>Linker2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Linker2</em>'.
   * @see org.xtext.gameuno.unoDsl.Exigence#getLinker2()
   * @see #getExigence()
   * @generated
   */
  EAttribute getExigence_Linker2();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.gameuno.unoDsl.Exigence#getCarte <em>Carte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Carte</em>'.
   * @see org.xtext.gameuno.unoDsl.Exigence#getCarte()
   * @see #getExigence()
   * @generated
   */
  EReference getExigence_Carte();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.Exigence#getLinker3 <em>Linker3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Linker3</em>'.
   * @see org.xtext.gameuno.unoDsl.Exigence#getLinker3()
   * @see #getExigence()
   * @generated
   */
  EAttribute getExigence_Linker3();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.Exigence#getExpr2 <em>Expr2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expr2</em>'.
   * @see org.xtext.gameuno.unoDsl.Exigence#getExpr2()
   * @see #getExigence()
   * @generated
   */
  EAttribute getExigence_Expr2();

  /**
   * Returns the meta object for class '{@link org.xtext.gameuno.unoDsl.Carte <em>Carte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Carte</em>'.
   * @see org.xtext.gameuno.unoDsl.Carte
   * @generated
   */
  EClass getCarte();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.Carte#getCouleur <em>Couleur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Couleur</em>'.
   * @see org.xtext.gameuno.unoDsl.Carte#getCouleur()
   * @see #getCarte()
   * @generated
   */
  EAttribute getCarte_Couleur();

  /**
   * Returns the meta object for class '{@link org.xtext.gameuno.unoDsl.CarteClassique <em>Carte Classique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Carte Classique</em>'.
   * @see org.xtext.gameuno.unoDsl.CarteClassique
   * @generated
   */
  EClass getCarteClassique();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gameuno.unoDsl.CarteClassique#getNumeroCarte <em>Numero Carte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero Carte</em>'.
   * @see org.xtext.gameuno.unoDsl.CarteClassique#getNumeroCarte()
   * @see #getCarteClassique()
   * @generated
   */
  EAttribute getCarteClassique_NumeroCarte();

  /**
   * Returns the meta object for class '{@link org.xtext.gameuno.unoDsl.CarteActive <em>Carte Active</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Carte Active</em>'.
   * @see org.xtext.gameuno.unoDsl.CarteActive
   * @generated
   */
  EClass getCarteActive();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UnoDslFactory getUnoDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.gameuno.unoDsl.impl.UnoDslImpl <em>Uno Dsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gameuno.unoDsl.impl.UnoDslImpl
     * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getUnoDsl()
     * @generated
     */
    EClass UNO_DSL = eINSTANCE.getUnoDsl();

    /**
     * The meta object literal for the '<em><b>Regles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNO_DSL__REGLES = eINSTANCE.getUnoDsl_Regles();

    /**
     * The meta object literal for the '{@link org.xtext.gameuno.unoDsl.impl.RegleJeuImpl <em>Regle Jeu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gameuno.unoDsl.impl.RegleJeuImpl
     * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getRegleJeu()
     * @generated
     */
    EClass REGLE_JEU = eINSTANCE.getRegleJeu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGLE_JEU__NAME = eINSTANCE.getRegleJeu_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGLE_JEU__DESCRIPTION = eINSTANCE.getRegleJeu_Description();

    /**
     * The meta object literal for the '<em><b>Exigence</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGLE_JEU__EXIGENCE = eINSTANCE.getRegleJeu_Exigence();

    /**
     * The meta object literal for the '{@link org.xtext.gameuno.unoDsl.impl.ExigenceImpl <em>Exigence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gameuno.unoDsl.impl.ExigenceImpl
     * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getExigence()
     * @generated
     */
    EClass EXIGENCE = eINSTANCE.getExigence();

    /**
     * The meta object literal for the '<em><b>Expr1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXIGENCE__EXPR1 = eINSTANCE.getExigence_Expr1();

    /**
     * The meta object literal for the '<em><b>Linker1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXIGENCE__LINKER1 = eINSTANCE.getExigence_Linker1();

    /**
     * The meta object literal for the '<em><b>Linker2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXIGENCE__LINKER2 = eINSTANCE.getExigence_Linker2();

    /**
     * The meta object literal for the '<em><b>Carte</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXIGENCE__CARTE = eINSTANCE.getExigence_Carte();

    /**
     * The meta object literal for the '<em><b>Linker3</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXIGENCE__LINKER3 = eINSTANCE.getExigence_Linker3();

    /**
     * The meta object literal for the '<em><b>Expr2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXIGENCE__EXPR2 = eINSTANCE.getExigence_Expr2();

    /**
     * The meta object literal for the '{@link org.xtext.gameuno.unoDsl.impl.CarteImpl <em>Carte</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gameuno.unoDsl.impl.CarteImpl
     * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getCarte()
     * @generated
     */
    EClass CARTE = eINSTANCE.getCarte();

    /**
     * The meta object literal for the '<em><b>Couleur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARTE__COULEUR = eINSTANCE.getCarte_Couleur();

    /**
     * The meta object literal for the '{@link org.xtext.gameuno.unoDsl.impl.CarteClassiqueImpl <em>Carte Classique</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gameuno.unoDsl.impl.CarteClassiqueImpl
     * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getCarteClassique()
     * @generated
     */
    EClass CARTE_CLASSIQUE = eINSTANCE.getCarteClassique();

    /**
     * The meta object literal for the '<em><b>Numero Carte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARTE_CLASSIQUE__NUMERO_CARTE = eINSTANCE.getCarteClassique_NumeroCarte();

    /**
     * The meta object literal for the '{@link org.xtext.gameuno.unoDsl.impl.CarteActiveImpl <em>Carte Active</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gameuno.unoDsl.impl.CarteActiveImpl
     * @see org.xtext.gameuno.unoDsl.impl.UnoDslPackageImpl#getCarteActive()
     * @generated
     */
    EClass CARTE_ACTIVE = eINSTANCE.getCarteActive();

  }

} //UnoDslPackage
