/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.gameuno.unoDsl.UnoDslPackage
 * @generated
 */
public interface UnoDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UnoDslFactory eINSTANCE = org.xtext.gameuno.unoDsl.impl.UnoDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Uno Dsl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uno Dsl</em>'.
   * @generated
   */
  UnoDsl createUnoDsl();

  /**
   * Returns a new object of class '<em>Regle Jeu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Regle Jeu</em>'.
   * @generated
   */
  RegleJeu createRegleJeu();

  /**
   * Returns a new object of class '<em>Exigence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exigence</em>'.
   * @generated
   */
  Exigence createExigence();

  /**
   * Returns a new object of class '<em>Carte</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Carte</em>'.
   * @generated
   */
  Carte createCarte();

  /**
   * Returns a new object of class '<em>Carte Classique</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Carte Classique</em>'.
   * @generated
   */
  CarteClassique createCarteClassique();

  /**
   * Returns a new object of class '<em>Carte Active</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Carte Active</em>'.
   * @generated
   */
  CarteActive createCarteActive();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UnoDslPackage getUnoDslPackage();

} //UnoDslFactory
