/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno Dsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gameuno.unoDsl.UnoDsl#getRegles <em>Regles</em>}</li>
 * </ul>
 *
 * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getUnoDsl()
 * @model
 * @generated
 */
public interface UnoDsl extends EObject
{
  /**
   * Returns the value of the '<em><b>Regles</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.gameuno.unoDsl.RegleJeu}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regles</em>' containment reference list.
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#getUnoDsl_Regles()
   * @model containment="true"
   * @generated
   */
  EList<RegleJeu> getRegles();

} // UnoDsl
