/*
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.gameuno.unodsl.ui.internal.UnodslActivator;

public class UnoDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UnodslActivator.getInstance().getInjector("org.xtext.gameuno.UnoDsl");
	}

}
