/*
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UnoDslUiModule extends AbstractUnoDslUiModule {

	public UnoDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
