/*
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UnoDslStandaloneSetup extends UnoDslStandaloneSetupGenerated {

	public static void doSetup() {
		new UnoDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
