/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.gameuno.unoDsl.CarteClassique;
import org.xtext.gameuno.unoDsl.UnoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Carte Classique</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gameuno.unoDsl.impl.CarteClassiqueImpl#getNumeroCarte <em>Numero Carte</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CarteClassiqueImpl extends CarteImpl implements CarteClassique
{
  /**
   * The default value of the '{@link #getNumeroCarte() <em>Numero Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumeroCarte()
   * @generated
   * @ordered
   */
  protected static final int NUMERO_CARTE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumeroCarte() <em>Numero Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumeroCarte()
   * @generated
   * @ordered
   */
  protected int numeroCarte = NUMERO_CARTE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CarteClassiqueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoDslPackage.Literals.CARTE_CLASSIQUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumeroCarte()
  {
    return numeroCarte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumeroCarte(int newNumeroCarte)
  {
    int oldNumeroCarte = numeroCarte;
    numeroCarte = newNumeroCarte;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.CARTE_CLASSIQUE__NUMERO_CARTE, oldNumeroCarte, numeroCarte));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTE_CLASSIQUE__NUMERO_CARTE:
        return getNumeroCarte();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTE_CLASSIQUE__NUMERO_CARTE:
        setNumeroCarte((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTE_CLASSIQUE__NUMERO_CARTE:
        setNumeroCarte(NUMERO_CARTE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTE_CLASSIQUE__NUMERO_CARTE:
        return numeroCarte != NUMERO_CARTE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (numeroCarte: ");
    result.append(numeroCarte);
    result.append(')');
    return result.toString();
  }

} //CarteClassiqueImpl
