/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.gameuno.unoDsl.CarteActive;
import org.xtext.gameuno.unoDsl.UnoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Carte Active</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CarteActiveImpl extends CarteImpl implements CarteActive
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CarteActiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoDslPackage.Literals.CARTE_ACTIVE;
  }

} //CarteActiveImpl
