/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.gameuno.unoDsl.Carte;
import org.xtext.gameuno.unoDsl.CarteActive;
import org.xtext.gameuno.unoDsl.CarteClassique;
import org.xtext.gameuno.unoDsl.Exigence;
import org.xtext.gameuno.unoDsl.RegleJeu;
import org.xtext.gameuno.unoDsl.UnoDsl;
import org.xtext.gameuno.unoDsl.UnoDslFactory;
import org.xtext.gameuno.unoDsl.UnoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UnoDslPackageImpl extends EPackageImpl implements UnoDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass unoDslEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass regleJeuEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exigenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass carteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass carteClassiqueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass carteActiveEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.gameuno.unoDsl.UnoDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private UnoDslPackageImpl()
  {
    super(eNS_URI, UnoDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link UnoDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static UnoDslPackage init()
  {
    if (isInited) return (UnoDslPackage)EPackage.Registry.INSTANCE.getEPackage(UnoDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredUnoDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    UnoDslPackageImpl theUnoDslPackage = registeredUnoDslPackage instanceof UnoDslPackageImpl ? (UnoDslPackageImpl)registeredUnoDslPackage : new UnoDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theUnoDslPackage.createPackageContents();

    // Initialize created meta-data
    theUnoDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theUnoDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(UnoDslPackage.eNS_URI, theUnoDslPackage);
    return theUnoDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUnoDsl()
  {
    return unoDslEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUnoDsl_Regles()
  {
    return (EReference)unoDslEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRegleJeu()
  {
    return regleJeuEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRegleJeu_Name()
  {
    return (EAttribute)regleJeuEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRegleJeu_Description()
  {
    return (EAttribute)regleJeuEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRegleJeu_Exigence()
  {
    return (EReference)regleJeuEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExigence()
  {
    return exigenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExigence_Expr1()
  {
    return (EAttribute)exigenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExigence_Linker1()
  {
    return (EAttribute)exigenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExigence_Linker2()
  {
    return (EAttribute)exigenceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExigence_Carte()
  {
    return (EReference)exigenceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExigence_Linker3()
  {
    return (EAttribute)exigenceEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExigence_Expr2()
  {
    return (EAttribute)exigenceEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCarte()
  {
    return carteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCarte_Couleur()
  {
    return (EAttribute)carteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCarteClassique()
  {
    return carteClassiqueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCarteClassique_NumeroCarte()
  {
    return (EAttribute)carteClassiqueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCarteActive()
  {
    return carteActiveEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UnoDslFactory getUnoDslFactory()
  {
    return (UnoDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    unoDslEClass = createEClass(UNO_DSL);
    createEReference(unoDslEClass, UNO_DSL__REGLES);

    regleJeuEClass = createEClass(REGLE_JEU);
    createEAttribute(regleJeuEClass, REGLE_JEU__NAME);
    createEAttribute(regleJeuEClass, REGLE_JEU__DESCRIPTION);
    createEReference(regleJeuEClass, REGLE_JEU__EXIGENCE);

    exigenceEClass = createEClass(EXIGENCE);
    createEAttribute(exigenceEClass, EXIGENCE__EXPR1);
    createEAttribute(exigenceEClass, EXIGENCE__LINKER1);
    createEAttribute(exigenceEClass, EXIGENCE__LINKER2);
    createEReference(exigenceEClass, EXIGENCE__CARTE);
    createEAttribute(exigenceEClass, EXIGENCE__LINKER3);
    createEAttribute(exigenceEClass, EXIGENCE__EXPR2);

    carteEClass = createEClass(CARTE);
    createEAttribute(carteEClass, CARTE__COULEUR);

    carteClassiqueEClass = createEClass(CARTE_CLASSIQUE);
    createEAttribute(carteClassiqueEClass, CARTE_CLASSIQUE__NUMERO_CARTE);

    carteActiveEClass = createEClass(CARTE_ACTIVE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    carteClassiqueEClass.getESuperTypes().add(this.getCarte());
    carteActiveEClass.getESuperTypes().add(this.getCarte());

    // Initialize classes and features; add operations and parameters
    initEClass(unoDslEClass, UnoDsl.class, "UnoDsl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUnoDsl_Regles(), this.getRegleJeu(), null, "regles", null, 0, -1, UnoDsl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(regleJeuEClass, RegleJeu.class, "RegleJeu", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRegleJeu_Name(), ecorePackage.getEString(), "name", null, 0, 1, RegleJeu.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRegleJeu_Description(), ecorePackage.getEString(), "description", null, 0, 1, RegleJeu.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRegleJeu_Exigence(), this.getExigence(), null, "exigence", null, 0, -1, RegleJeu.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exigenceEClass, Exigence.class, "Exigence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExigence_Expr1(), ecorePackage.getEString(), "expr1", null, 0, 1, Exigence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExigence_Linker1(), ecorePackage.getEString(), "linker1", null, 0, 1, Exigence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExigence_Linker2(), ecorePackage.getEString(), "linker2", null, 0, 1, Exigence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExigence_Carte(), this.getCarte(), null, "carte", null, 0, -1, Exigence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExigence_Linker3(), ecorePackage.getEString(), "linker3", null, 0, 1, Exigence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExigence_Expr2(), ecorePackage.getEString(), "expr2", null, 0, 1, Exigence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(carteEClass, Carte.class, "Carte", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCarte_Couleur(), ecorePackage.getEString(), "couleur", null, 0, 1, Carte.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(carteClassiqueEClass, CarteClassique.class, "CarteClassique", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCarteClassique_NumeroCarte(), ecorePackage.getEInt(), "numeroCarte", null, 0, 1, CarteClassique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(carteActiveEClass, CarteActive.class, "CarteActive", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Create resource
    createResource(eNS_URI);
  }

} //UnoDslPackageImpl
