/**
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.unoDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.gameuno.unoDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UnoDslFactoryImpl extends EFactoryImpl implements UnoDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static UnoDslFactory init()
  {
    try
    {
      UnoDslFactory theUnoDslFactory = (UnoDslFactory)EPackage.Registry.INSTANCE.getEFactory(UnoDslPackage.eNS_URI);
      if (theUnoDslFactory != null)
      {
        return theUnoDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new UnoDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UnoDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case UnoDslPackage.UNO_DSL: return createUnoDsl();
      case UnoDslPackage.REGLE_JEU: return createRegleJeu();
      case UnoDslPackage.EXIGENCE: return createExigence();
      case UnoDslPackage.CARTE: return createCarte();
      case UnoDslPackage.CARTE_CLASSIQUE: return createCarteClassique();
      case UnoDslPackage.CARTE_ACTIVE: return createCarteActive();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UnoDsl createUnoDsl()
  {
    UnoDslImpl unoDsl = new UnoDslImpl();
    return unoDsl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RegleJeu createRegleJeu()
  {
    RegleJeuImpl regleJeu = new RegleJeuImpl();
    return regleJeu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Exigence createExigence()
  {
    ExigenceImpl exigence = new ExigenceImpl();
    return exigence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Carte createCarte()
  {
    CarteImpl carte = new CarteImpl();
    return carte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CarteClassique createCarteClassique()
  {
    CarteClassiqueImpl carteClassique = new CarteClassiqueImpl();
    return carteClassique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CarteActive createCarteActive()
  {
    CarteActiveImpl carteActive = new CarteActiveImpl();
    return carteActive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UnoDslPackage getUnoDslPackage()
  {
    return (UnoDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static UnoDslPackage getPackage()
  {
    return UnoDslPackage.eINSTANCE;
  }

} //UnoDslFactoryImpl
