/*
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UnoDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/gameuno/parser/antlr/internal/InternalUnoDsl.tokens");
	}
}
