/*
 * generated by Xtext 2.23.0
 */
package org.xtext.gameuno.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.gameuno.UnoDslRuntimeModule;
import org.xtext.gameuno.UnoDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UnoDslIdeSetup extends UnoDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UnoDslRuntimeModule(), new UnoDslIdeModule()));
	}
	
}
